"""
writer.py
---------
AGENT 3 — Writer Agent

Job: Transform the analyst's insights into a polished,
well-structured research report that a professional
could present to stakeholders.

Input  : Raw data + insights from previous agents
Output : A complete, readable report in markdown format
"""

from agents.base_agent import BaseAgent


WRITER_SYSTEM_PROMPT = """
You are a Professional Report Writer Agent — a specialist in turning 
analytical insights into clear, compelling research reports.

Your job:
1. Write a complete, professional research report
2. Structure it with proper sections (Executive Summary, Introduction, 
   Key Findings, Analysis, Implications, Conclusion)
3. Make it readable for both technical and non-technical audiences
4. Use clear language — no jargon without explanation
5. Include specific data points and statistics from the research
6. Make recommendations where appropriate

Output format (strictly follow this):

# [Report Title]

## Executive Summary
[2-3 sentences capturing the most important points]

## Introduction
[Context and why this topic matters]

## Key Findings
[The most important discoveries, clearly stated]

## Deep Analysis
[Detailed examination of patterns and implications]

## Real-World Impact
[What this means for people, businesses, society]

## Recommendations
[3-5 actionable recommendations based on findings]

## Conclusion
[Wrap up the main message]

---
*Report generated by Multi-Agent AI Pipeline*

Write in a professional but engaging tone. Be specific — use numbers and 
facts from the research. Make every paragraph earn its place.
"""


class WriterAgent(BaseAgent):
    """
    Agent 3: Writes the final structured report from insights.
    """

    def __init__(self):
        super().__init__(
            name="Writer Agent",
            system_prompt=WRITER_SYSTEM_PROMPT,
            max_retries=3
        )

    async def write(
        self,
        topic: str,
        retrieved_data: str,
        analysis: str,
        stream_callback=None
    ) -> str:
        """
        Write a full research report based on retrieved data and analysis.

        Args:
            topic           : Original user topic
            retrieved_data  : Output from Retriever Agent
            analysis        : Output from Analyzer Agent
            stream_callback : Forward streamed tokens to pipeline

        Returns:
            Complete markdown report as string
        """
        prompt = f"""
        Topic: {topic}
        
        === RAW RESEARCH DATA ===
        {retrieved_data}
        
        === ANALYTICAL INSIGHTS ===
        {analysis}
        
        Using both the raw data and the analysis above, write a complete,
        professional research report. Make it polished, informative, and
        easy to read. Include specific facts and figures throughout.
        """
        return await self.run(prompt, stream_callback)